spring:
  datasource:
    url: jdbc:mysql://localhost:656/jwt_security
    username: root
    password: KHmoussi5*
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        platform: mysql
server:
  port: 8010


